# Generated by Django 5.2.7 on 2025-11-03 20:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('money', 'Money/Fundraising'), ('job', 'Job/Employment'), ('travel', 'Travel/Visit'), ('other', 'Other')], default='money', max_length=20)),
                ('target_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Target amount for fundraising', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('raised_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('target_description', models.TextField(blank=True, help_text='Description of goal (for job, travel, other)')),
                ('deadline', models.DateField(blank=True, null=True)),
                ('milestones', models.JSONField(default=list, help_text='List of milestone objects with title, amount, and reached status')),
                ('is_active', models.BooleanField(default=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='goal', to='posts.post')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoalContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('message', models.TextField(blank=True)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=255)),
                ('stripe_payment_intent', models.CharField(blank=True, max_length=255)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='completed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='posts.goal')),
                ('supporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_contributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoalContributionComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_comments', to=settings.AUTH_USER_MODEL)),
                ('contribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.goalcontribution')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='posts.goalcontributioncomment')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['post', 'is_active'], name='posts_goal_post_id_5b94f3_idx'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['goal_type', 'is_active'], name='posts_goal_goal_ty_6b62b8_idx'),
        ),
        migrations.AddIndex(
            model_name='goalcontribution',
            index=models.Index(fields=['goal', '-created_at'], name='posts_goalc_goal_id_e71a52_idx'),
        ),
        migrations.AddIndex(
            model_name='goalcontribution',
            index=models.Index(fields=['supporter', '-created_at'], name='posts_goalc_support_9484b8_idx'),
        ),
        migrations.AddIndex(
            model_name='goalcontribution',
            index=models.Index(fields=['payment_status'], name='posts_goalc_payment_6bd4bf_idx'),
        ),
        migrations.AddIndex(
            model_name='goalcontributioncomment',
            index=models.Index(fields=['contribution', 'created_at'], name='posts_goalc_contrib_949a86_idx'),
        ),
        migrations.AddIndex(
            model_name='goalcontributioncomment',
            index=models.Index(fields=['parent_comment', 'created_at'], name='posts_goalc_parent__d71f4f_idx'),
        ),
    ]
