# Generated by Django 5.2.7 on 2025-11-04 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0003_goal_goalcontribution_goalcontributioncomment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('service_type', models.CharField(choices=[('face_verification', 'Face Verification'), ('liveness_detection', 'Liveness Detection'), ('document_verification', 'Document Verification'), ('image_moderation', 'Image Content Moderation')], max_length=30)),
                ('provider', models.CharField(choices=[('local', 'Local (Self-hosted)'), ('openai', 'OpenAI'), ('google', 'Google Cloud Vision'), ('aws', 'AWS Rekognition'), ('azure', 'Azure Face API'), ('deepface', 'DeepFace'), ('mediapipe', 'MediaPipe')], max_length=100)),
                ('api_key', models.CharField(blank=True, max_length=500)),
                ('api_endpoint', models.URLField(blank=True, max_length=500)),
                ('model_version', models.CharField(blank=True, max_length=50)),
                ('min_confidence_score', models.FloatField(default=80.0)),
                ('min_face_match_score', models.FloatField(default=85.0)),
                ('min_liveness_score', models.FloatField(default=75.0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('config_json', models.JSONField(default=dict)),
                ('daily_request_limit', models.IntegerField(default=1000)),
                ('monthly_request_limit', models.IntegerField(default=30000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('national_id', 'National ID'), ('passport', 'Passport'), ('drivers_license', "Driver's License"), ('certificate', 'Certificate'), ('bank_statement', 'Bank Statement'), ('other', 'Other')], max_length=50)),
                ('document_image_url', models.URLField(max_length=500)),
                ('document_back_image_url', models.URLField(blank=True, max_length=500)),
                ('extracted_text', models.TextField(blank=True)),
                ('extracted_data', models.JSONField(default=dict, help_text='Structured data: name, DOB, ID number, etc')),
                ('document_is_valid', models.BooleanField(default=False)),
                ('document_is_authentic', models.BooleanField(default=False)),
                ('document_is_expired', models.BooleanField(default=False)),
                ('face_match_with_profile', models.BooleanField(blank=True, null=True)),
                ('face_match_score', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('passed', 'Passed'), ('failed', 'Failed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('verification_results', models.JSONField(default=dict)),
                ('ai_model_used', models.CharField(default='tesseract-ocr', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FaceVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_type', models.CharField(choices=[('face_verification', 'Face Verification'), ('liveness_detection', 'Liveness Detection'), ('document_verification', 'Document Verification'), ('image_moderation', 'Image Content Moderation')], default='face_verification', max_length=30)),
                ('reference_image_url', models.URLField(help_text='Original profile/ID photo', max_length=500)),
                ('verification_image_url', models.URLField(help_text='Live captured photo', max_length=500)),
                ('liveness_required', models.BooleanField(default=True)),
                ('liveness_actions_required', models.JSONField(default=list, help_text="List of required actions: ['smile', 'open_mouth', 'blink']")),
                ('liveness_actions_completed', models.JSONField(default=list, help_text='List of completed actions with timestamps')),
                ('liveness_video_url', models.URLField(blank=True, max_length=500)),
                ('face_match_score', models.FloatField(blank=True, help_text='Similarity score 0-100', null=True)),
                ('liveness_score', models.FloatField(blank=True, help_text='Liveness detection score 0-100', null=True)),
                ('confidence_score', models.FloatField(blank=True, help_text='Overall confidence 0-100', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('passed', 'Passed'), ('failed', 'Failed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('ai_model_used', models.CharField(default='deepface', help_text='AI model: deepface, face-api, mediapipe, etc', max_length=100)),
                ('ai_provider', models.CharField(default='local', help_text='Provider: local, aws-rekognition, azure-face, etc', max_length=100)),
                ('analysis_results', models.JSONField(default=dict, help_text='Full AI analysis response')),
                ('failure_reason', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device_info', models.JSONField(blank=True, default=dict)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-initiated_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='ai_services_user_id_888e2d_idx'), models.Index(fields=['verification_type', 'status'], name='ai_services_verific_13f850_idx'), models.Index(fields=['-initiated_at'], name='ai_services_initiat_160ea4_idx')],
            },
        ),
        migrations.CreateModel(
            name='ImageModeration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500)),
                ('image_type', models.CharField(choices=[('profile', 'Profile Picture'), ('post', 'Post Image'), ('document', 'Document'), ('other', 'Other')], max_length=50)),
                ('is_safe', models.BooleanField(default=True)),
                ('is_appropriate', models.BooleanField(default=True)),
                ('contains_nudity', models.BooleanField(default=False)),
                ('contains_violence', models.BooleanField(default=False)),
                ('contains_offensive_content', models.BooleanField(default=False)),
                ('contains_text', models.BooleanField(default=False)),
                ('nudity_score', models.FloatField(default=0.0)),
                ('violence_score', models.FloatField(default=0.0)),
                ('offensive_score', models.FloatField(default=0.0)),
                ('detected_labels', models.JSONField(default=list, help_text='List of detected labels/objects in image')),
                ('detected_text', models.TextField(blank=True)),
                ('ai_model_used', models.CharField(default='vision-api', max_length=100)),
                ('moderation_results', models.JSONField(default=dict)),
                ('auto_rejected', models.BooleanField(default=False)),
                ('flagged_for_review', models.BooleanField(default=False)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_images', to='posts.post')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_safe'], name='ai_services_user_id_ab8a26_idx'), models.Index(fields=['image_type', '-created_at'], name='ai_services_image_t_535b03_idx')],
            },
        ),
    ]
