# Generated by Django 5.2.7 on 2025-11-01 19:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0002_initial'),
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('tuition', 'Tuition Fee'), ('materials', 'Learning Materials'), ('equipment', 'Equipment'), ('stipend', 'Living Stipend'), ('transportation', 'Transportation'), ('accommodation', 'Accommodation'), ('healthcare', 'Healthcare'), ('other', 'Other')], max_length=50)),
                ('budget_breakdown', models.JSONField(blank=True, help_text='Detailed breakdown of how funds will be used', null=True)),
                ('supporting_documents', models.JSONField(default=list, help_text='List of document URLs')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_date', models.DateField()),
                ('actual_date', models.DateField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=100, unique=True)),
                ('receipt_url', models.URLField(max_length=500)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('emailed_to', models.EmailField(blank=True, max_length=254)),
                ('emailed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('transaction_type', models.CharField(choices=[('donation', 'Donation Received'), ('disbursement', 'Fund Disbursement'), ('refund', 'Refund'), ('adjustment', 'Balance Adjustment'), ('fee', 'Platform Fee')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('sender_name', models.CharField(blank=True, max_length=255)),
                ('sender_email', models.EmailField(blank=True, max_length=254)),
                ('sender_phone', models.CharField(blank=True, max_length=20)),
                ('recipient_name', models.CharField(blank=True, max_length=255)),
                ('recipient_account', models.CharField(blank=True, max_length=100)),
                ('recipient_bank', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('blockchain_hash', models.CharField(max_length=64, unique=True)),
                ('previous_block_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('receipt_url', models.URLField(blank=True, max_length=500, null=True)),
                ('invoice_url', models.URLField(blank=True, max_length=500, null=True)),
                ('proof_of_payment_url', models.URLField(blank=True, max_length=500, null=True)),
                ('description', models.TextField()),
                ('internal_notes', models.TextField(blank=True, help_text='Private admin notes')),
                ('payment_gateway', models.CharField(blank=True, max_length=50)),
                ('gateway_reference', models.CharField(blank=True, max_length=255)),
                ('gateway_response', models.JSONField(blank=True, null=True)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story', models.TextField(help_text="Beneficiary's story and background")),
                ('impact_statement', models.TextField(blank=True, help_text='How the program impacted them')),
                ('amount_received', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('amount_spent', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('location', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='Nigeria', max_length=100)),
                ('age_bracket', models.CharField(blank=True, choices=[('18-24', '18-24 years'), ('25-34', '25-34 years'), ('35-44', '35-44 years'), ('45-54', '45-54 years'), ('55+', '55+ years')], max_length=20)),
                ('is_public', models.BooleanField(default=True, help_text='Show on public transparency page')),
                ('display_name', models.CharField(help_text='Public display name (can be anonymized)', max_length=255)),
                ('profile_image_url', models.URLField(blank=True, max_length=500)),
                ('joined_date', models.DateField()),
                ('expected_completion_date', models.DateField(blank=True, null=True)),
                ('actual_completion_date', models.DateField(blank=True, null=True)),
                ('completion_percentage', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('milestones_completed', models.PositiveIntegerField(default=0)),
                ('total_milestones', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('discontinued', 'Discontinued')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiary_record', to='applications.application')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to='programs.program')),
            ],
            options={
                'verbose_name_plural': 'Beneficiaries',
                'ordering': ['-created_at'],
            },
        ),
    ]
