# Generated by Django 5.2.7 on 2025-11-10 23:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatPrivacySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view_status', models.BooleanField(default=True, help_text='Can see online/offline status')),
                ('can_view_profile', models.BooleanField(default=True, help_text='Can view full profile')),
                ('can_call', models.BooleanField(default=True, help_text='Can make voice calls')),
                ('can_video_call', models.BooleanField(default=True, help_text='Can make video calls')),
                ('can_send_donate_request', models.BooleanField(default=True, help_text='Can send donation requests')),
                ('can_tag', models.BooleanField(default=True, help_text='Can tag in posts')),
                ('mute_notifications', models.BooleanField(default=False)),
                ('blocked_until', models.DateTimeField(blank=True, help_text='Temporary block expiry time', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='The user who owns these settings', on_delete=django.db.models.deletion.CASCADE, related_name='chat_privacy_settings', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(help_text='The user these settings apply to', on_delete=django.db.models.deletion.CASCADE, related_name='received_privacy_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Privacy Setting',
                'verbose_name_plural': 'Chat Privacy Settings',
                'ordering': ['-updated_at'],
                'unique_together': {('owner', 'target_user')},
            },
        ),
    ]
