# Generated by Django 5.2.7 on 2025-11-01 19:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.CharField(choices=[('healthcare', 'Healthcare'), ('skills', 'Skills Training'), ('housing', 'Housing Support'), ('education', 'Education')], max_length=20)),
                ('description', models.TextField()),
                ('reason', models.TextField(help_text='Why this program was established')),
                ('cover_image', models.URLField(max_length=500)),
                ('thumbnail_image', models.URLField(blank=True, max_length=500, null=True)),
                ('intro_video_url', models.URLField(blank=True, max_length=500, null=True)),
                ('intro_video_thumbnail', models.URLField(blank=True, max_length=500, null=True)),
                ('intro_video_duration', models.CharField(blank=True, max_length=10, null=True)),
                ('intro_video_title', models.CharField(blank=True, max_length=255, null=True)),
                ('total_spots', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('spots_filled', models.PositiveIntegerField(default=0)),
                ('start_date', models.DateTimeField()),
                ('close_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open for Applications'), ('closing_soon', 'Closing Soon'), ('closed', 'Closed'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('total_beneficiaries', models.PositiveIntegerField(default=0)),
                ('total_funds_disbursed', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('success_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('how_to_apply', models.TextField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgramBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit_description', models.CharField(max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProgramCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterion_name', models.CharField(max_length=255)),
                ('criterion_description', models.TextField()),
                ('weight_percentage', models.DecimalField(decimal_places=2, help_text='Percentage weight in evaluation', max_digits=5)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Program criteria',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProgramExecutive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('can_approve', models.BooleanField(default=True)),
                ('can_reject', models.BooleanField(default=True)),
                ('is_primary_reviewer', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProgramQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement', models.CharField(max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProgramRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=255)),
                ('is_required', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProgramTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_name', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProgramUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('likes_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-posted_at'],
            },
        ),
    ]
