# Generated by Django 5.2.7 on 2025-11-01 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_programs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='programbenefit',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='programs.program'),
        ),
        migrations.AddField(
            model_name='programcriteria',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='programs.program'),
        ),
        migrations.AddField(
            model_name='programexecutive',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executives', to='programs.program'),
        ),
        migrations.AddField(
            model_name='programexecutive',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executive_programs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='programqualification',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='programs.program'),
        ),
        migrations.AddField(
            model_name='programrequirement',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='programs.program'),
        ),
        migrations.AddField(
            model_name='programtimeline',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='programs.program'),
        ),
        migrations.AddField(
            model_name='programupdate',
            name='posted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='programupdate',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='programs.program'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['status', 'category'], name='programs_pr_status_fc5438_idx'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['close_date'], name='programs_pr_close_d_d0f467_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='programexecutive',
            unique_together={('program', 'user')},
        ),
    ]
