# Generated by Django 5.2.7 on 2025-11-04 12:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0003_goal_goalcontribution_goalcontributioncomment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('payment_method', models.CharField(choices=[('paystack', 'Paystack'), ('flutterwave', 'Flutterwave'), ('blockchain', 'Blockchain'), ('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money')], max_length=30)),
                ('network_type', models.CharField(choices=[('testnet', 'Test Network'), ('mainnet', 'Main Network')], default='testnet', max_length=20)),
                ('public_key', models.CharField(blank=True, max_length=500)),
                ('secret_key', models.CharField(blank=True, max_length=500)),
                ('merchant_id', models.CharField(blank=True, max_length=255)),
                ('api_base_url', models.URLField(max_length=500)),
                ('webhook_url', models.URLField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('transaction_fee_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('fixed_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('min_amount', models.DecimalField(decimal_places=2, default=100, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_amount', models.DecimalField(decimal_places=2, default=1000000, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['payment_method', 'is_active'], name='payments_pa_payment_4a8859_idx'), models.Index(fields=['network_type'], name='payments_pa_network_3057b5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('gateway_reference', models.CharField(blank=True, db_index=True, max_length=255)),
                ('gateway_response', models.JSONField(blank=True, null=True)),
                ('network_type', models.CharField(choices=[('testnet', 'Test Network'), ('mainnet', 'Main Network')], default='testnet', max_length=20)),
                ('blockchain_hash', models.CharField(blank=True, db_index=True, max_length=100)),
                ('blockchain_address', models.CharField(blank=True, max_length=255)),
                ('purpose', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('is_refunded', models.BooleanField(default=False)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('refund_reason', models.TextField(blank=True)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='posts.post')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.paymentgateway')),
            ],
            options={
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('payload', models.JSONField()),
                ('headers', models.JSONField(default=dict)),
                ('is_processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_error', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='payments.paymentgateway')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhooks', to='payments.payment')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='BlockchainTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_type', models.CharField(choices=[('testnet', 'Test Network'), ('mainnet', 'Main Network')], max_length=20)),
                ('tx_hash', models.CharField(db_index=True, max_length=100, unique=True)),
                ('block_number', models.BigIntegerField(blank=True, null=True)),
                ('block_hash', models.CharField(blank=True, max_length=100)),
                ('from_address', models.CharField(max_length=255)),
                ('to_address', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=30)),
                ('gas_used', models.BigIntegerField(blank=True, null=True)),
                ('gas_price', models.DecimalField(blank=True, decimal_places=18, max_digits=30, null=True)),
                ('confirmations', models.IntegerField(default=0)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('raw_transaction', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blockchain_tx', to='payments.payment')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tx_hash'], name='payments_bl_tx_hash_415545_idx'), models.Index(fields=['network_type', 'is_confirmed'], name='payments_bl_network_76c9b9_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', 'status'], name='payments_pa_user_id_01767a_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['gateway', 'status'], name='payments_pa_gateway_7fb286_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['-initiated_at'], name='payments_pa_initiat_85233c_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['network_type', 'blockchain_hash'], name='payments_pa_network_3097be_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentwebhook',
            index=models.Index(fields=['gateway', 'is_processed'], name='payments_pa_gateway_5db2f1_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentwebhook',
            index=models.Index(fields=['event_type', '-received_at'], name='payments_pa_event_t_dd9f37_idx'),
        ),
    ]
