# Generated by Django 5.2.7 on 2025-11-01 19:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_interaction_at', models.DateTimeField(auto_now=True)),
                ('ai_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('ai_recommendation', models.TextField(blank=True, null=True)),
                ('total_messages', models.PositiveIntegerField(default=0)),
                ('flagged_responses', models.PositiveIntegerField(default=0)),
                ('full_transcript', models.JSONField(default=list, help_text='List of {role, message, timestamp} objects')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('video_pending', 'Video Pending'), ('ai_interview_pending', 'AI Interview Pending'), ('ai_interview_completed', 'AI Interview Completed'), ('under_review', 'Under Executive Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='draft', max_length=30)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('blockchain_hash', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_url', models.URLField(max_length=500)),
                ('document_name', models.CharField(max_length=255)),
                ('document_type', models.CharField(max_length=50)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ExecutiveReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scores', models.JSONField(help_text='Dictionary mapping criterion_id to score value')),
                ('total_score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('notes', models.TextField(blank=True)),
                ('strengths', models.TextField(blank=True, help_text='What the applicant did well')),
                ('weaknesses', models.TextField(blank=True, help_text='Areas of concern')),
                ('recommendation', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('revise', 'Request Revision')], max_length=20)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('time_spent_minutes', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(max_length=500)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500, null=True)),
                ('duration', models.PositiveIntegerField(help_text='Duration in seconds')),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('format', models.CharField(default='mp4', max_length=10)),
                ('transcript', models.TextField(blank=True, help_text='AI-generated transcript via Whisper', null=True)),
                ('transcript_generated_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AIInterviewMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'AI Assistant'), ('system', 'System')], max_length=20)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message_index', models.PositiveIntegerField(help_text='Order in conversation')),
                ('answer_verified', models.BooleanField(default=False)),
                ('flagged_for_review', models.BooleanField(default=False)),
                ('flag_reason', models.CharField(blank=True, max_length=255)),
                ('sentiment_score', models.DecimalField(blank=True, decimal_places=2, help_text='Sentiment analysis score from -1 to 1', max_digits=4, null=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='applications.aiinterview')),
            ],
            options={
                'ordering': ['interview', 'message_index'],
            },
        ),
    ]
