# Generated by Django 5.2.7 on 2025-11-01 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0002_initial'),
        ('programs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aiinterview',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_interview', to='applications.application'),
        ),
        migrations.AddField(
            model_name='applicationdocument',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='applications.application'),
        ),
        migrations.AddField(
            model_name='applicationdocument',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to='programs.programrequirement'),
        ),
        migrations.AddField(
            model_name='applicationdocument',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='executivereview',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executive_reviews', to='applications.application'),
        ),
        migrations.AddField(
            model_name='executivereview',
            name='executive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='programs.programexecutive'),
        ),
        migrations.AddField(
            model_name='videoapplication',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='applications.application'),
        ),
        migrations.AddIndex(
            model_name='aiinterviewmessage',
            index=models.Index(fields=['interview', 'timestamp'], name='application_intervi_6d8df1_idx'),
        ),
        migrations.AddIndex(
            model_name='aiinterviewmessage',
            index=models.Index(fields=['interview', 'message_index'], name='application_intervi_8fca74_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['user', 'status'], name='application_user_id_55b4e4_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['program', 'status'], name='application_program_36d099_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['blockchain_hash'], name='application_blockch_c09b6e_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['-submitted_at'], name='application_submitt_50a9ef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('user', 'program')},
        ),
        migrations.AddIndex(
            model_name='applicationdocument',
            index=models.Index(fields=['application', 'requirement'], name='application_applica_00c477_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationdocument',
            index=models.Index(fields=['is_verified'], name='application_is_veri_f48892_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='applicationdocument',
            unique_together={('application', 'requirement')},
        ),
        migrations.AddIndex(
            model_name='executivereview',
            index=models.Index(fields=['application', 'recommendation'], name='application_applica_84fc0b_idx'),
        ),
        migrations.AddIndex(
            model_name='executivereview',
            index=models.Index(fields=['executive', '-reviewed_at'], name='application_executi_a8c852_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='executivereview',
            unique_together={('application', 'executive')},
        ),
    ]
