# Generated by Django 5.2.7 on 2025-11-01 19:46

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('block_create', 'Block Created'), ('block_verify', 'Block Verified'), ('chain_verify', 'Chain Integrity Check'), ('query', 'Blockchain Query'), ('tampering_detected', 'Tampering Detected')], max_length=50)),
                ('details', models.JSONField(help_text='Full details of the action')),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='BlockchainStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_blocks', models.PositiveIntegerField(default=0)),
                ('total_transactions', models.PositiveIntegerField(default=0)),
                ('total_programs', models.PositiveIntegerField(default=0)),
                ('total_donations', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_disbursements', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_refunds', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('chain_integrity_verified', models.BooleanField(default=True)),
                ('last_integrity_check', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blockchain Statistics',
                'verbose_name_plural': 'Blockchain Statistics',
            },
        ),
        migrations.CreateModel(
            name='BlockchainTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_index', models.PositiveIntegerField(db_index=True, unique=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=datetime.datetime.now)),
                ('transaction_type', models.CharField(choices=[('donation', 'Donation Received'), ('disbursement', 'Fund Disbursement'), ('program_create', 'Program Creation'), ('application_submit', 'Application Submission'), ('application_approve', 'Application Approval'), ('beneficiary_add', 'Beneficiary Added'), ('refund', 'Refund Processed')], max_length=50)),
                ('transaction_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('data', models.JSONField(help_text='Complete transaction details including amounts, parties, and metadata')),
                ('previous_hash', models.CharField(db_index=True, max_length=64)),
                ('hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('nonce', models.PositiveIntegerField(default=0)),
                ('difficulty', models.PositiveIntegerField(default=4, help_text='Number of leading zeros required')),
                ('is_verified', models.BooleanField(default=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Blockchain Transaction',
                'verbose_name_plural': 'Blockchain Transactions',
                'ordering': ['block_index'],
            },
        ),
        migrations.CreateModel(
            name='TransactionChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('link_type', models.CharField(choices=[('direct', 'Direct Transfer'), ('split', 'Split Disbursement'), ('consolidation', 'Funds Consolidation'), ('refund', 'Refund Flow')], default='direct', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
