# Generated by Django 5.2.7 on 2025-11-01 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blockchain', '0001_initial'),
        ('programs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchainauditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blockchain_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blockchaintransaction',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blockchain_records', to='programs.program'),
        ),
        migrations.AddField(
            model_name='blockchaintransaction',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User associated with this transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blockchain_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blockchaintransaction',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_blocks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blockchainauditlog',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='blockchain.blockchaintransaction'),
        ),
        migrations.AddField(
            model_name='transactionchain',
            name='from_transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='blockchain.blockchaintransaction'),
        ),
        migrations.AddField(
            model_name='transactionchain',
            name='to_transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='blockchain.blockchaintransaction'),
        ),
        migrations.AddIndex(
            model_name='blockchaintransaction',
            index=models.Index(fields=['hash'], name='blockchain__hash_78d91e_idx'),
        ),
        migrations.AddIndex(
            model_name='blockchaintransaction',
            index=models.Index(fields=['transaction_id'], name='blockchain__transac_620ee8_idx'),
        ),
        migrations.AddIndex(
            model_name='blockchaintransaction',
            index=models.Index(fields=['block_index'], name='blockchain__block_i_5dd2f3_idx'),
        ),
        migrations.AddIndex(
            model_name='blockchaintransaction',
            index=models.Index(fields=['-timestamp'], name='blockchain__timesta_a51248_idx'),
        ),
        migrations.AddIndex(
            model_name='blockchaintransaction',
            index=models.Index(fields=['transaction_type', '-timestamp'], name='blockchain__transac_b463f6_idx'),
        ),
        migrations.AddIndex(
            model_name='blockchainauditlog',
            index=models.Index(fields=['-timestamp'], name='blockchain__timesta_f4a592_idx'),
        ),
        migrations.AddIndex(
            model_name='blockchainauditlog',
            index=models.Index(fields=['action', '-timestamp'], name='blockchain__action_e2e129_idx'),
        ),
        migrations.AddIndex(
            model_name='blockchainauditlog',
            index=models.Index(fields=['user', '-timestamp'], name='blockchain__user_id_70da6e_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionchain',
            index=models.Index(fields=['from_transaction', '-created_at'], name='blockchain__from_tr_a4bbfe_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionchain',
            index=models.Index(fields=['to_transaction', '-created_at'], name='blockchain__to_tran_8c70e3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='transactionchain',
            unique_together={('from_transaction', 'to_transaction')},
        ),
    ]
